module_name: PriceAlert - Follow the Price
compatible_versions: 1.0.0+
author: datakick
category: front office
tags:
  - price alert
  - alert
description_short: This module allows your customers to easily create price alerts and receive email when price drops
description: description.md
images:
  - image-1.png
  - image-2.png
  - image-3.png
license: MIT
php_version:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
